### ISSUE TITLE
Add click to copy on Libra short address on home page

### ISSUE THREAD

**Issue by totiz** [kulapio/libra-wallet-poc#30]

**Comment by suraneti** [comment]
@totiz I've merged copy wallet address on commit **4c54f99**.

**Comment by totiz** [comment]
<img width="1180" alt="Screen Shot 2562-08-23 at 14 32 00" src="https://user-images.githubusercontent.com/459912/63574948-23af0000-c5b3-11e9-8711-7b7bde0c67d4.png">

Could you please adjust like this?, I think just add copy icon is enough, and click on the line to copy (Wallet: 0xaabb...eeff [copy icon]).

What do you think?

**Comment by suraneti** [comment]
@totiz I agree, it looks cleaner in UI.

**Comment by suraneti** [comment]
@totiz Merged with commit **a64c3d9**.

**Comment by Nokomy** [comment]
I believe this is a start....however there are still a number of questions your design is asking for....Like exchange with other cryptos and major or local currency were it is adapted....otherwise we shall just have few options of the to currencies and this is not relevant to a local farmer or trader in My country....
Especially the need for other verification log-in and security on ones mobile app version....
And B.V.N and other regulatory and inter-bank transfer conversion for students and the ordinary man.
